<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.25">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>comparison – What Does India's Parliament Talk About?</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./output/figures/ideological_space.png" rel="icon" type="image/png">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-7b89279ff1a6dce999919e0e67d4d9ec.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-58f65581fc16a020bf8c0dce5340cfae.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<style>html{ scroll-behavior: smooth; }</style>


</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a href="./index.html" class="navbar-brand navbar-brand-logo">
    </a>
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">What Does India’s Parliament Talk About?</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="./index.html#findings"> 
<span class="menu-text">LS Analysis</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link active" href="./comparison.html" aria-current="page"> 
<span class="menu-text">LS vs RS</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./rs_analysis.html"> 
<span class="menu-text">RS Analysis</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./sule_report.html"> 
<span class="menu-text">MP Profile</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./index.html#methodology"> 
<span class="menu-text">Methodology</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://github.com/pzaware19/lok-sabha-nlp"> <i class="bi bi-github" role="img">
</i> 
<span class="menu-text">Code</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Contents</h2>
   
  <ul class="collapse">
  <li><a href="#two-houses-one-parliament-how-lok-sabha-and-rajya-sabha-ask-differently" id="toc-two-houses-one-parliament-how-lok-sabha-and-rajya-sabha-ask-differently" class="nav-link active" data-scroll-target="#two-houses-one-parliament-how-lok-sabha-and-rajya-sabha-ask-differently">Two Houses, One Parliament: How Lok Sabha and Rajya Sabha Ask Differently</a></li>
  <li><a href="#coverage" id="toc-coverage" class="nav-link" data-scroll-target="#coverage">Coverage and Scale</a></li>
  <li><a href="#volume" id="toc-volume" class="nav-link" data-scroll-target="#volume">The Volume Question: Who Drives Each House?</a></li>
  <li><a href="#vocabulary" id="toc-vocabulary" class="nav-link" data-scroll-target="#vocabulary">What Words Separate the Two Houses?</a></li>
  <li><a href="#language" id="toc-language" class="nav-link" data-scroll-target="#language">Linguistic Register: Hindi Framing vs English vs Regional</a></li>
  <li><a href="#ministry" id="toc-ministry" class="nav-link" data-scroll-target="#ministry">Ministry Targeting: Same Party, Same Ministries?</a></li>
  <li><a href="#discipline" id="toc-discipline" class="nav-link" data-scroll-target="#discipline">Party Discipline: Does the Upper House Coordinate Better?</a></li>
  <li><a href="#adversarialism" id="toc-adversarialism" class="nav-link" data-scroll-target="#adversarialism">Adversarialism: Which House is More Confrontational?</a></li>
  <li><a href="#idealpoints" id="toc-idealpoints" class="nav-link" data-scroll-target="#idealpoints">The Constituency Hypothesis: Test Results</a></li>
  <li><a href="#interpretation" id="toc-interpretation" class="nav-link" data-scroll-target="#interpretation">What This Comparison Tells Us</a></li>
  <li><a href="#method" id="toc-method" class="nav-link" data-scroll-target="#method">Methodology Note</a></li>
  <li><a href="#about" id="toc-about" class="nav-link" data-scroll-target="#about">About</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block"></header>




<section id="two-houses-one-parliament-how-lok-sabha-and-rajya-sabha-ask-differently" class="level1 hero">
<h1>Two Houses, One Parliament: How Lok Sabha and Rajya Sabha Ask Differently</h1>
<div class="subtitle">
<p>India’s Parliament has two chambers with nearly identical legislative powers but very different electoral mandates. One is elected directly from 543 constituencies. The other represents states. Running the same NLP pipeline on both produces a clean natural experiment: what happens to parliamentary language when you remove the constituency?</p>
</div>
<div class="meta">
<p>Piyush Zaware</p>
</div>
<div class="badge-row">
<div class="badge-item">
<p>4,315 LS Questions</p>
</div>
<div class="badge-item">
<p>9,315 RS Questions</p>
</div>
<div class="badge-item">
<p>860 LS MPs · 264 RS Members</p>
</div>
<div class="badge-item">
<p>SVD · TF-IDF · BING Sentiment</p>
</div>
<div class="badge-item">
<p>2014 – 2026</p>
</div>
</div>
</section>
<p>Lok Sabha starred questions come from MPs who won individual seats. The question they ask this session reflects their constituency’s needs as much as their party’s ideology. A BJP MP from coastal Andhra will ask about fisheries. A Congress MP from Chhattisgarh will ask about forest rights. Party affiliation is one signal among several.</p>
<p>Rajya Sabha members are elected by state legislatures, not voters. They have no individual constituency to service. If the constituency pull is the main reason Lok Sabha parties don’t cluster by ideology in their questioning vocabulary, Rajya Sabha members should show clearer party-line vocabulary differences. That is the hypothesis this comparison tests.</p>
<hr>
<section id="coverage" class="level2">
<h2 class="anchored" data-anchor-id="coverage">Coverage and Scale</h2>
<div class="stat-row">
  <div class="stat"><div class="stat-num">4,315</div><div class="stat-label">LS starred questions</div></div>
  <div class="stat"><div class="stat-num">9,315</div><div class="stat-label">RS starred questions</div></div>
  <div class="stat"><div class="stat-num">860</div><div class="stat-label">LS MPs matched</div></div>
  <div class="stat"><div class="stat-num">264</div><div class="stat-label">RS members matched</div></div>
</div>
<p>Lok Sabha generates roughly 22% more starred questions in aggregate, despite the two houses being closer in formal power than that ratio suggests. The gap reflects how the instruments function in practice: starred questions in Lok Sabha are partly constituency signalling tools, so there is structural incentive to ask more of them. RS members face no such incentive from voters.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th></th>
<th>Lok Sabha</th>
<th>Rajya Sabha</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Starred questions (matched)</td>
<td>4,315</td>
<td>9,315</td>
</tr>
<tr class="even">
<td>Members / MPs matched</td>
<td>860</td>
<td>264</td>
</tr>
<tr class="odd">
<td>Match rate</td>
<td>95.5%</td>
<td>96.7%</td>
</tr>
<tr class="even">
<td>Houses / period</td>
<td>16th–18th LS (2014–2026)</td>
<td>2014–2025</td>
</tr>
<tr class="odd">
<td>Party-vocabulary B/W ratio</td>
<td>0.8206</td>
<td>0.2255</td>
</tr>
</tbody>
</table>
<hr>
</section>
<section id="volume" class="level2">
<h2 class="anchored" data-anchor-id="volume">The Volume Question: Who Drives Each House?</h2>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="output/figures/compare_question_volume.png" class="img-fluid figure-img" style="width:90.0%"></p>
<figcaption>Starred questions per matched member, by party and house (2014-2025). The metric normalises for both party size and house size, isolating question-asking intensity at the individual member level.</figcaption>
</figure>
</div>
<p>The raw question count misleads. BJP held 282-303 seats across the 16th and 17th Lok Sabhas, which mechanically produces a large absolute volume. And Rajya Sabha has 245 seats to Lok Sabha’s 543, which compresses RS totals before any party-level comparison. The per-member rate strips both of those confounds.</p>
<p>The result is striking: <strong>across every single party, RS members ask dramatically more questions per person than their LS counterparts</strong> – roughly 5 to 10 times more. This is not a BJP-specific finding; it holds for INC, Left, TMC, SP, and every other party in the data.</p>
<p>The explanation is structural. Lok Sabha starred questions are distributed by lottery across a house of 543 members. When BJP holds 300 of those seats, each INC MP gets fewer draws. In Rajya Sabha, the seat distribution was more balanced throughout the Modi era – BJP typically held 35-40% of seats, not 55-56% – so opposition members had proportionally more floor access.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Party-specific patterns worth noting
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>BJP</strong> is the only party whose RS rate (around 18 questions per member) is <em>lower</em> than that of most opposition parties in RS. Governing party backbenchers have limited incentive to use starred questions to hold their own government accountable. That BJP RS members ask 18 questions per member at all reflects that RS was not under BJP majority for much of this period.</p>
<p><strong>DMK</strong> has a near-zero LS bar (essentially no matched LS questions) but 34 questions per RS member. DMK had very few Lok Sabha seats in the 16th and 17th parliaments – they were locked out at the national level. Rajya Sabha, filled via Tamil Nadu’s state assembly, was their only consistent national platform through those years.</p>
<p><strong>JDU and AAP</strong> follow the same pattern. Their LS presence is too thin to register, but their RS members are highly active, using the upper house as a national megaphone that constituency elections had not yet granted them.</p>
<p>Regional parties – TDP, SP, DMK – cluster at the top in RS rates, above 30 questions per member. These are small national parties with focused issue agendas and no obligation to distribute their questions across hundreds of diverse constituencies. They concentrate their RS access intensely.</p>
</div>
</div>
<hr>
</section>
<section id="vocabulary" class="level2">
<h2 class="anchored" data-anchor-id="vocabulary">What Words Separate the Two Houses?</h2>
<p>The simplest question: are the vocabularies of the two houses actually different? Take all question titles from both houses, compute word frequencies, and ask which words appear disproportionately in one versus the other.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="output/figures/compare_vocab_logratio.png" class="img-fluid figure-img" style="width:90.0%"></p>
<figcaption>Log2 ratio of word frequency in RS vs LS question titles. Orange bars point rightward = that word appears proportionally more in Rajya Sabha. Blue bars point leftward = that word is more characteristic of Lok Sabha.</figcaption>
</figure>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>What the vocabulary split reveals
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Rajya Sabha distinctive words</strong> trend toward the abstract and constitutional: <em>policy</em>, <em>rights</em>, <em>bill</em>, <em>national</em>, <em>regulation</em>, <em>agreement</em>, <em>amendment</em>, <em>trade</em>. These are the words of deliberative policy debate. A Rajya Sabha member asking about trade agreements or proposed legislation is operating in the register appropriate to a chamber that reviews laws rather than delivering constituency services.</p>
<p><strong>Lok Sabha distinctive words</strong> trend toward the concrete and local: <em>pradesh</em>, <em>districts</em>, <em>state</em>, <em>village</em>, <em>construction</em>, <em>pending</em>, <em>demand</em>, <em>implementation</em>. These are the words of constituency oversight. A Lok Sabha MP asking why the construction of a state highway is pending in their district is using parliament as a direct accountability instrument for local delivery.</p>
<p>This vocabulary split is the clearest empirical signal of the two houses operating differently. The constitutional difference (constituency vs state representation) shows up directly in the language MPs choose.</p>
</div>
</div>
<section id="how-vocabulary-shifts-within-parties" class="level3">
<h3 class="anchored" data-anchor-id="how-vocabulary-shifts-within-parties">How vocabulary shifts within parties</h3>
<p>The overall split hides interesting variation across parties. The same party’s language changes depending on which house its members are sitting in.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="output/figures/compare_party_fingerprints.png" class="img-fluid figure-img" style="width:100.0%"></p>
<figcaption>For BJP, INC, Left, and TMC: words used proportionally more in RS questions vs LS questions. Orange = more RS; blue = more LS. Reveals how each party’s questioning strategy changes across chambers.</figcaption>
</figure>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Party-specific shifts
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>BJP</strong> shifts from infrastructure and scheme-specific vocabulary in Lok Sabha (where its large MP contingent asks about roads, funds, pradhan mantri schemes at the constituency level) toward more national policy vocabulary in Rajya Sabha.</p>
<p><strong>INC</strong> shows a smaller shift, consistent with its opposition role in both houses. In Lok Sabha, INC MPs concentrate on accountability questions about specific government actions. In Rajya Sabha, INC language tilts toward constitutional and legislative vocabulary, where the upper house is the better venue for challenging government bills.</p>
<p><strong>Left</strong> shows the most pronounced shift. In Lok Sabha, Left MPs concentrated heavily on Kerala and West Bengal constituency concerns. In Rajya Sabha, where they have no local constituency, their vocabulary converges on labour rights and national policy terms – the ideological core they fall back on when constituency pull disappears.</p>
<p><strong>TMC</strong> in Lok Sabha is almost entirely West Bengal-focused. In Rajya Sabha, the constituency anchor is loosened, and TMC members broaden into national welfare and rights vocabulary.</p>
</div>
</div>
<hr>
</section>
</section>
<section id="language" class="level2">
<h2 class="anchored" data-anchor-id="language">Linguistic Register: Hindi Framing vs English vs Regional</h2>
<p>Indian Parliament officially functions in Hindi and English, with members permitted to speak in any scheduled language. But all starred question titles in this dataset are recorded in Latin script – either English or transliterated Hindi and regional terms. The question is whether parties differ systematically in how much they rely on Hindi-origin policy vocabulary versus English framing, and whether that pattern changes between houses.</p>
<p>The measure is a lexicon-based count: what proportion of each party’s question titles contain at least one recognisably Hindi-origin policy term (yojana, kisan, swachh, jal, vikas, mudra, bima, krishi, gram, shakti, etc.) rather than the English equivalent (scheme, farmer, clean, water, development, loan, crop, village, empowerment).</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="output/figures/compare_hindi_intensity.png" class="img-fluid figure-img" style="width:90.0%"></p>
<figcaption>% of starred question titles containing at least one transliterated Hindi policy term, by party. Connected dots show the same party in LS (blue) vs RS (gold). Parties to the right use more Hindi framing.</figcaption>
</figure>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>What the Hindi intensity comparison shows
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Left parties consistently use the least Hindi-origin vocabulary</strong> in both houses (under 2% in LS, under 3% in RS). This fits Kerala’s long-standing resistance to Hindi imposition – Left MPs from Kerala and West Bengal systematically prefer English framing for policy questions, even when asking about centrally-sponsored schemes that carry Hindi names.</p>
<p><strong>TMC uses the most Hindi vocabulary in Lok Sabha (6.6%)</strong> – higher than BJP. This is counterintuitive at first but makes sense: TMC LS members in constituencies across West Bengal ask heavily about central government schemes (PMAY, PMGSY, PMJDY) that BJP has branded with Hindi names. Asking about these schemes in Lok Sabha requires using BJP’s vocabulary. In Rajya Sabha (4.9%), where TMC members are more likely to debate policy design than local delivery, the Hindi framing drops.</p>
<p><strong>BJP’s Hindi vocabulary increases from LS (4.1%) to RS (5.1%)</strong>. In LS, BJP members are the governing party defending implementation – they often use English administrative vocabulary. In RS, where BJP faced a more adversarial floor during much of this period, members appear to lean harder into Hindi policy framing as a positioning choice.</p>
<p><strong>RJD</strong> (Rashtriya Janata Dal – Hindi-belt Bihar) shows the largest RS jump: 3.3% LS to 6.2% RS. Hindi is both the natural language and the political identity marker for Bihar-based parties; the RS platform amplifies that.</p>
<p><strong>TDP</strong> is consistently low in both houses (~3.5%), consistent with Andhra Pradesh’s position in the anti-Hindi imposition bloc.</p>
</div>
</div>
<section id="regional-geographic-vocabulary-rs-as-a-platform-for-state-advocacy" class="level3">
<h3 class="anchored" data-anchor-id="regional-geographic-vocabulary-rs-as-a-platform-for-state-advocacy">Regional geographic vocabulary: RS as a platform for state advocacy</h3>
<p>The second linguistic signal is geographic – which parties invoke place names from their home region in question titles.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="output/figures/compare_regional_markers.png" class="img-fluid figure-img" style="width:95.0%"></p>
<figcaption>Regional geographic markers in RS question titles, by party. Only RS bars are shown because southern parties (DMK, AIADMK, TDP) have too few LS matched questions for comparison. The markers capture Tamil, Telugu, and Bengali geographic place names appearing in question titles.</figcaption>
</figure>
</div>
<p>The pattern here validates a straightforward claim: <strong>Rajya Sabha functions as the primary national platform for regional parties</strong>. AIADMK and DMK invoke Tamil geographic vocabulary (Cauvery, Mettur, Madurai, Tuticorin) in about 1% of their RS questions. TDP invokes Telugu geographic markers (Polavaram, Godavari, Rayalaseema) in 2.6% of RS questions – the highest rate of any regional geographic marker. TMC references Bengali geography (Sundarbans, Hooghly, Damodar) in 0.2% of RS questions.</p>
<p>These numbers are small as proportions, but the asymmetry is the finding: these parties do not have enough Lok Sabha seats to appear in the LS data at all during this period. Their national geographic advocacy is conducted entirely through the upper house.</p>
</section>
<section id="combined-register-overview" class="level3">
<h3 class="anchored" data-anchor-id="combined-register-overview">Combined register overview</h3>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="output/figures/compare_lang_heatmap.png" class="img-fluid figure-img" style="width:90.0%"></p>
<figcaption>Linguistic register summary: % of questions with Hindi policy terms (left) and regional geographic markers (right), by party and house. A richer blue = higher prevalence.</figcaption>
</figure>
</div>
<hr>
</section>
</section>
<section id="ministry" class="level2">
<h2 class="anchored" data-anchor-id="ministry">Ministry Targeting: Same Party, Same Ministries?</h2>
<p>Parties have consistent strategic priorities around which ministries to scrutinise. But do those priorities survive the shift from a constituency-based house to a state-based one?</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="output/figures/compare_ministry_focus.png" class="img-fluid figure-img" style="width:100.0%"></p>
<figcaption>Ministry targeting by party in Lok Sabha (left) vs Rajya Sabha (right). Cell colour = % of that party’s questions directed to each ministry.</figcaption>
</figure>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>The ministries that shift most between houses
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Finance</strong> is more heavily targeted in Rajya Sabha across all major parties. The upper house is the natural venue for scrutinising fiscal policy – it has no constituency-specific infrastructure spending to track, so questions gravitate toward national macroeconomic and banking policy.</p>
<p><strong>Railways and Road Transport</strong> dominate Lok Sabha targeting. These are the two ministries most directly tied to constituency-level infrastructure spending. An MP asking why a road project is delayed or when a new railway station will open is doing classic constituency work that has no analog in Rajya Sabha.</p>
<p><strong>Home Affairs</strong> and <strong>Labour</strong> show a more symmetric pattern: both houses scrutinise these ministries at roughly the same rate, with opposition parties concentrating there regardless of chamber. This makes sense – internal security and employment are not constituency-specific concerns; they are national policy debates.</p>
<p>The pattern supports a clean institutional interpretation: parties use Lok Sabha for constituency accountability, Rajya Sabha for national policy scrutiny. The party-level priorities (which party focuses on which ministry) are consistent across houses, but the <em>type</em> of question asked changes.</p>
</div>
</div>
<section id="rajya-sabha-ministry-excess-targeting" class="level3">
<h3 class="anchored" data-anchor-id="rajya-sabha-ministry-excess-targeting">Rajya Sabha ministry excess targeting</h3>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="output/figures/rs_ministry_excess_heatmap.png" class="img-fluid figure-img" style="width:95.0%"></p>
<figcaption>Pearson residuals for RS ministry targeting. Red = party over-questions this ministry relative to its overall question share; blue = under-questions. The pattern broadly mirrors Lok Sabha but with finance and home affairs more pronounced.</figcaption>
</figure>
</div>
<hr>
</section>
</section>
<section id="discipline" class="level2">
<h2 class="anchored" data-anchor-id="discipline">Party Discipline: Does the Upper House Coordinate Better?</h2>
<p>A disciplined parliamentary party’s MPs ask about the same topics using similar vocabulary. The discipline score is the average cosine similarity between each member’s TF-IDF vector and the party’s centroid. Higher = more coordinated questioning.</p>
<p>The constituency hypothesis predicts RS members should be more disciplined than LS MPs: without individual constituency agendas pulling them in different directions, they should converge on a shared party vocabulary.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="output/figures/compare_discipline.png" class="img-fluid figure-img" style="width:90.0%"></p>
<figcaption>Discipline scores by party in both houses. Connected dots show the same party in LS (blue) and RS (orange). A dot moving rightward when going from LS to RS means RS members are more coordinated.</figcaption>
</figure>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>The discipline finding: modest convergence, not transformation
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>BJP RS discipline (0.185) vs LS (0.105)</strong>: RS members are 76% more disciplined. BJP sends far fewer members to Rajya Sabha than to Lok Sabha, and without the constituency heterogeneity of 68 members from very different states, the centroid is easier to converge on.</p>
<p><strong>INC RS discipline (0.201) vs LS (0.166)</strong>: The INC pattern mirrors BJP. Fewer RS members, more coherent opposition agenda, slightly higher discipline.</p>
<p><strong>The general pattern</strong>: nearly all parties show higher discipline in Rajya Sabha, consistent with the constituency pull hypothesis. But the magnitude of the shift is modest. Discipline roughly doubles from the lowest-discipline parties, but it does not reach the level of true caucus coordination one would expect in a whipped chamber. Indian parties, in both houses, give their members substantial latitude on what to ask about.</p>
<p><strong>Smaller parties</strong> (Left, DMK, BJD, JDU) score high on discipline in both houses. Their members are already highly focused on a narrow issue set regardless of chamber, so the constituency removal makes little additional difference.</p>
</div>
</div>
<hr>
</section>
<section id="adversarialism" class="level2">
<h2 class="anchored" data-anchor-id="adversarialism">Adversarialism: Which House is More Confrontational?</h2>
<p>Opposition parties use starred questions as accountability tools. But does the nature of the chamber affect how adversarial the questioning gets? Lok Sabha MPs face re-election and may moderate aggressive questioning to maintain local relationships. Rajya Sabha members, insulated from direct voter accountability, might be freer to confront.</p>
<p>Sentiment is measured using the BING positive/negative lexicon applied to question titles. A question is classified as adversarial if its title contains more negative than positive words. The measure captures adversarial framing (shortage, failure, delay, violation) vs aspirational framing (promotion, welfare, development, scheme).</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="output/figures/compare_adversarialism.png" class="img-fluid figure-img" style="width:90.0%"></p>
<figcaption>Adversarialism rate (% of questions with net-negative BING sentiment) by party in both houses. Connected dots show LS (blue) vs RS (orange).</figcaption>
</figure>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>What the adversarialism comparison shows
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Left parties</strong> are the most adversarial in both houses, with 70.1% of their RS question titles scoring net-negative in BING sentiment. This is consistent across chambers: left parties adopt an adversarial stance as a matter of strategic identity.</p>
<p><strong>The RS-vs-LS gap is small</strong>. Most parties show similar adversarialism rates in both houses. This suggests that the tone of parliamentary questioning is a party-level strategic choice, not a function of how insulated the member is from voters. A party that frames questions adversarially in Lok Sabha does the same in Rajya Sabha.</p>
<p><strong>The exception is regional parties</strong> (DMK, AIADMK, BJD), which show somewhat higher adversarialism in RS than LS. In LS, these parties balance adversarial questions with aspirational constituency-service questions. In RS, without the aspirational constituency component, the balance tips toward confrontation.</p>
<p><strong>BJP</strong> is consistently the least adversarial in both houses, which is structurally expected: government parties ask fewer critical questions about their own policies. The slight uptick in RS adversarialism for BJP may reflect RS members, with longer terms and no constituency to protect, occasionally willing to criticise implementation gaps that their LS colleagues prefer to gloss over.</p>
</div>
</div>
<hr>
</section>
<section id="idealpoints" class="level2">
<h2 class="anchored" data-anchor-id="idealpoints">The Constituency Hypothesis: Test Results</h2>
<p>The main theoretical question: does removing constituency variation (by moving from LS to RS) produce more party-based vocabulary sorting in the ideal point space?</p>
<p>The test runs the identical truncated SVD pipeline on both houses. If constituency variation is the main reason Lok Sabha parties don’t cluster by ideology, Rajya Sabha parties should cluster more clearly.</p>
<section id="party-clustering-between-party-vs-within-party-variance" class="level3">
<h3 class="anchored" data-anchor-id="party-clustering-between-party-vs-within-party-variance">Party clustering: between-party vs within-party variance</h3>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="output/figures/compare_bw_ratio.png" class="img-fluid figure-img" style="width:70.0%"></p>
<figcaption>Between-party variance / within-party variance on the primary SVD dimension, Lok Sabha vs Rajya Sabha. A higher ratio means more party-based sorting.</figcaption>
</figure>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Interpreting the variance ratio
</div>
</div>
<div class="callout-body-container callout-body">
<p>The between/within ratio for Lok Sabha is <strong>0.8206</strong>. For Rajya Sabha it is <strong>0.2255</strong> – lower, not higher.</p>
<p>This is the opposite of what the constituency hypothesis predicts, and the reason is worth being precise about. LS is dominated by BJP, which accounts for roughly 52% of matched questions. BJP’s vocabulary as the governing party (infrastructure achievements, scheme rollouts, development targets) is systematically different from every opposition party’s vocabulary (failures, delays, accountability). That contrast inflates the between-party component in LS mechanically. In Rajya Sabha, where BJP held 35-40% of seats rather than 55%, the dominant-party effect is weaker, and the ratio falls.</p>
<p>Put differently: the LS B/W ratio captures a governing-vs-opposition vocabulary split as much as party ideology. The RS ratio is smaller because the house is closer to balance, and with no single party dominating, vocabulary variation spreads within rather than between parties.</p>
<p>In both houses, the absolute level is far below US Congress NOMINATE (&gt;10). India’s parliamentary parties do not enforce coordinated question vocabularies. Members ask about what they know, where they are from, and what their committee positions require – not what a party whip mandates.</p>
</div>
</div>
</section>
<section id="ideal-point-maps-ls-vs-rs" class="level3">
<h3 class="anchored" data-anchor-id="ideal-point-maps-ls-vs-rs">Ideal point maps: LS vs RS</h3>
<div class="quarto-layout-panel" data-layout-ncol="2">
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="output/figures/ideal_2d.png" class="img-fluid figure-img"></p>
<figcaption>Lok Sabha: 860 MPs in 2D SVD space. Party centroids (diamonds) cluster near the origin with wide within-party spread.</figcaption>
</figure>
</div>
</div>
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="output/figures/rs_ideal_2d.png" class="img-fluid figure-img"></p>
<figcaption>Rajya Sabha: 264 members in 2D SVD space. Centroids show slightly more separation, but within-party variance still dominates.</figcaption>
</figure>
</div>
</div>
</div>
</div>
</section>
<section id="distribution-along-the-primary-dimension" class="level3">
<h3 class="anchored" data-anchor-id="distribution-along-the-primary-dimension">Distribution along the primary dimension</h3>
<div class="quarto-layout-panel" data-layout-ncol="2">
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="output/figures/ideal_dim1_party.png" class="img-fluid figure-img"></p>
<figcaption>LS Dimension 1 distributions by party. Distributions heavily overlap. The primary axis is geographic/sectoral, not ideological.</figcaption>
</figure>
</div>
</div>
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="output/figures/rs_dim1_party.png" class="img-fluid figure-img"></p>
<figcaption>RS Dimension 1 distributions by party. BJP and INC are now visibly separated, but the overlap remains substantial.</figcaption>
</figure>
</div>
</div>
</div>
</div>
<p>The two distribution plots make the constituency hypothesis concrete. In Lok Sabha (left), the BJP and INC distributions are nearly identical – they cover the same vocabulary space because their MPs come from similar mixes of states and constituency types. In Rajya Sabha (right), a gap opens up. BJP members lean toward one vocabulary register, INC toward another. But the gap is far narrower than what you would expect if party ideology were the primary driver of question content.</p>
<hr>
</section>
</section>
<section id="interpretation" class="level2">
<h2 class="anchored" data-anchor-id="interpretation">What This Comparison Tells Us</h2>
<div class="stat-row">
  <div class="stat"><div class="stat-num">5–10x</div><div class="stat-label">more questions per RS member than LS</div></div>
  <div class="stat"><div class="stat-num">&lt; 1.0</div><div class="stat-label">between/within ratio in both houses</div></div>
  <div class="stat"><div class="stat-num">10+</div><div class="stat-label">NOMINATE ratio for US Congress</div></div>
</div>
<p>The comparison across houses produces three conclusions.</p>
<p><strong>The vocabulary split is real.</strong> LS questions are more local in language (pradesh, districts, construction, pending); RS questions are more national (policy, bill, rights, regulation). This is exactly what the constitutional difference between the houses predicts, and it shows up cleanly in the log-ratio chart. The per-member question rate is also dramatically higher in RS – 5 to 10 times higher across every party – because RS offered a more level platform when BJP held supermajorities in LS.</p>
<p><strong>Party clustering does not increase in the upper house.</strong> The between/within variance ratio is higher in Lok Sabha (B/W = 0.8206) than in Rajya Sabha (0.2255). This appears to reflect the governing-vs-opposition contrast that BJP’s LS dominance creates, rather than genuine ideological polarisation. In both houses, the ratio is far below what US NOMINATE finds for Congress (&gt;10). Party affiliation explains a small fraction of what any individual member asks about.</p>
<p><strong>Party strategy is more durable than party discipline.</strong> The ministry-level comparison shows that parties maintain consistent targeting strategies across houses – INC focuses on Finance and Home Affairs in both, Left concentrates on Labour in both, regional parties track their state-specific ministries in both. But within those strategic preferences, members have enormous latitude on exact vocabulary and framing. The parties know which ministries to scrutinise; they leave their members to figure out how.</p>
<section id="the-institutional-implication" class="level3">
<h3 class="anchored" data-anchor-id="the-institutional-implication">The institutional implication</h3>
<p>India’s two-house system does not produce two distinct types of parliamentary questioning in the way the constitutional theory predicts. Both houses show weak party coordination. Both show vocabulary driven more by individual background than collective party agenda. The upper house produces more policy-oriented language and slightly more party clustering, but not a qualitatively different mode of legislative behaviour.</p>
<p>The Rajya Sabha is not, in practice, a deliberative chamber of states in the way the Westminster Lords or US Senate function. It is closer to a second Lok Sabha with state-based rather than constituency-based member selection – and that difference does show up in the data, but as degree rather than kind.</p>
<hr>
</section>
</section>
<section id="method" class="level2">
<h2 class="anchored" data-anchor-id="method">Methodology Note</h2>
<p>All analyses on this page use matched starred questions from both houses (match rates: LS 95.5%, RS 96.7%). The matching pipeline, TF-IDF construction, truncated SVD, and discipline scoring are identical across houses, making the comparison clean. Sentiment uses the BING positive/negative lexicon applied to question titles, chosen for its availability and interpretability. The between/within variance ratio is computed on the primary SVD dimension; the absolute values should not be compared directly to NOMINATE, which uses a different decomposition and different legislative instrument (roll-call votes vs question vocabulary).</p>
<p>The analysis compares institutions, not individuals. Claims about “BJP” or “INC” behaviour are claims about the aggregate of their members’ questions, not about any specific MP’s intent.</p>
<hr>
</section>
<section id="about" class="level2">
<h2 class="anchored" data-anchor-id="about">About</h2>
<p><strong>Piyush Zaware</strong></p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
            // target, if specified
            link.setAttribute("target", "_blank");
            if (link.getAttribute("rel") === null) {
              link.setAttribute("rel", "noopener");
            }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
      &nbsp;
    </div>   
    <div class="nav-footer-center">
<p>Piyush Zaware</p>
</div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>




<script src="site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>