<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.25">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>What Does India’s Parliament Talk About?</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./output/figures/ideological_space.png" rel="icon" type="image/png">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-7b89279ff1a6dce999919e0e67d4d9ec.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-80a66261715bbc0e3b0f6d065ea9bc03.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<style>html{ scroll-behavior: smooth; }</style>


</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a href="./index.html" class="navbar-brand navbar-brand-logo">
    </a>
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">What Does India’s Parliament Talk About?</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="./index.html#findings"> 
<span class="menu-text">Findings</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./index.html#methodology"> 
<span class="menu-text">Methodology</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://github.com/pzaware19/lok-sabha-nlp"> <i class="bi bi-github" role="img">
</i> 
<span class="menu-text">Code</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Contents</h2>
   
  <ul class="collapse">
  <li><a href="#what-does-indias-parliament-actually-talk-about" id="toc-what-does-indias-parliament-actually-talk-about" class="nav-link active" data-scroll-target="#what-does-indias-parliament-actually-talk-about">What Does India’s Parliament Actually Talk About?</a></li>
  <li><a href="#data" id="toc-data" class="nav-link" data-scroll-target="#data">The Data</a></li>
  <li><a href="#methodology" id="toc-methodology" class="nav-link" data-scroll-target="#methodology">How It Works</a></li>
  <li><a href="#findings" id="toc-findings" class="nav-link" data-scroll-target="#findings">Key Findings</a></li>
  <li><a href="#reproduce" id="toc-reproduce" class="nav-link" data-scroll-target="#reproduce">Reproducing the Analysis</a></li>
  <li><a href="#about" id="toc-about" class="nav-link" data-scroll-target="#about">About</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block"></header>




<section id="what-does-indias-parliament-actually-talk-about" class="level1 hero">
<h1>What Does India’s Parliament Actually Talk About?</h1>
<div class="subtitle">
<p>Mapping the ideological landscape of Indian democracy from 150,000 parliamentary questions using unsupervised machine learning. No labels, no hand-coding, just text.</p>
</div>
<div class="meta">
<p>Piyush Zaware</p>
</div>
<div class="badge-row">
<div class="badge-item">
<p>150,000 Questions</p>
</div>
<div class="badge-item">
<p>16th – 18th Lok Sabha (2014–2026)</p>
</div>
<div class="badge-item">
<p>13 Parties</p>
</div>
<div class="badge-item">
<p>LDA · STM · Word2Vec · UMAP</p>
</div>
</div>
</section>
<p>Every parliamentary session, Indian MPs submit hundreds of written questions to government ministries. These are not speeches or debates. They are targeted, on-the-record demands for information: what is the government doing about farmer suicides, what is the status of highway construction in Bihar, how many minorities were displaced last year. Taken together, across three Lok Sabhas and 13 parties, they form a detailed paper trail of what each party actually cares about.</p>
<p>This project mines the complete archive of starred (oral) questions from the 16th, 17th, and 18th Lok Sabha using unsupervised machine learning. The central question: <strong>can you recover the ideological map of Indian politics purely from how MPs phrase their questions, without any human annotation?</strong></p>
<p>The answer is yes, and the results are sharper than expected.</p>
<hr>
<section id="data" class="level2">
<h2 class="anchored" data-anchor-id="data">The Data</h2>
<div class="finding-strip">
<div class="finding-card">
<div class="number">
<p>150K</p>
</div>
<div class="label">
<p>Total parliamentary questions across the 16th, 17th, and 18th Lok Sabha</p>
</div>
</div>
<div class="finding-card">
<div class="number">
<p>13</p>
</div>
<div class="label">
<p>Parties covered: BJP, INC, Left, BSP, AAP, TMC, SP, JDU, DMK, TDP, RJD, Shiv Sena, Regional</p>
</div>
</div>
<div class="finding-card">
<div class="number">
<p>205</p>
</div>
<div class="label">
<p>Documents in the corpus (one per party per parliamentary session)</p>
</div>
</div>
</div>
<p>The dataset is the <a href="https://huggingface.co/datasets/opensansad/lok-sabha-qa"><code>opensansad/lok-sabha-qa</code></a> corpus on HuggingFace: 150,629 questions covering the 16th (2014–2019), 17th (2019–2024), and 18th (2024–) Lok Sabha. The analysis focuses on <strong>starred questions</strong>, the oral variety submitted by MPs before each session. Starred questions are richer in political content than unstarred written submissions. A minister must be present to answer them in the House, which means parties use them strategically.</p>
<p>MP-to-party mapping was constructed by scraping Wikipedia’s constituency member lists for all three Lok Sabhas (three pages, automated, no API needed). This yielded a 38% match rate on starred questions, covering BJP, INC, and most major opposition parties with sufficient observations for reliable estimation.</p>
<p>After matching, the corpus was preprocessed into <strong>205 party-session documents</strong>: one document per party per parliamentary session, treated as the unit of analysis. Each document is the concatenated text of all starred questions submitted by that party in that session.</p>
<table class="caption-top table">
<tbody>
<tr class="odd">
<td>Total questions</td>
<td>150,629</td>
</tr>
<tr class="even">
<td>Starred questions</td>
<td>11,881</td>
</tr>
<tr class="odd">
<td>Starred with party match</td>
<td>4,356</td>
</tr>
<tr class="even">
<td>Unique MPs matched</td>
<td>1,642</td>
</tr>
<tr class="odd">
<td>Party-session documents</td>
<td>205</td>
</tr>
<tr class="even">
<td>Vocabulary (after pruning)</td>
<td>3,258 terms</td>
</tr>
</tbody>
</table>
<hr>
</section>
<section id="methodology" class="level2">
<h2 class="anchored" data-anchor-id="methodology">How It Works</h2>
<p>The pipeline runs end-to-end in R from a single command.</p>
<pre><code>source("code/_master.R")</code></pre>
<pre><code>Raw Questions (150K)
       │
  A1: Download        ← HuggingFace parquet files, no authentication
       │
  A2: Party Labels    ← Wikipedia scrape, MP to party lookup
       │
  A3: Preprocess      ← Tokenize, stem, remove boilerplate, build DTM
       │              ← 205 party×session documents, 3,258-term vocabulary
       │
  ┌────┴────────────┬──────────────────┐
  ▼                 ▼                  ▼
A4: LDA         A5: STM           A6: Word2Vec
K=15 topics     K=20 topics       Kozlowski (2019)
party heatmap   + party/time      ideological dims
                covariates
  └────┬────────────┴──────────────────┘
       │
  A7: Clustering   ← HAC + GMM Gaussian mixture on TF-IDF PCA
       │
  A8: Visualization ← UMAP, t-SNE, stacked area, heatmaps</code></pre>
<section id="methods" class="level3">
<h3 class="anchored" data-anchor-id="methods">Methods</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 27%">
<col style="width: 44%">
<col style="width: 27%">
</colgroup>
<thead>
<tr class="header">
<th>Method</th>
<th>What it does</th>
<th>Key output</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>LDA</strong> (Latent Dirichlet Allocation)</td>
<td>Discovers K recurring topics without supervision. Each document is a mixture of topics; each topic is a distribution over words.</td>
<td>15 topics, each party’s topic weights</td>
</tr>
<tr class="even">
<td><strong>STM</strong> (Structural Topic Model)</td>
<td>Extends LDA by allowing party identity and Lok Sabha number to shift topic prevalence. Asks: does BJP talk about topic 7 more than INC, and did that change over time?</td>
<td>Marginal effects of party on each topic</td>
</tr>
<tr class="odd">
<td><strong>Word2Vec + Kozlowski (2019)</strong></td>
<td>Trains a 100-dimensional word embedding on all 150K questions. Recovers ideological dimensions as directions in embedding space using antonym pairs.</td>
<td>Party scores on Hindutva, Left-Right, Rural-Urban axes</td>
</tr>
<tr class="even">
<td><strong>HAC</strong> (Hierarchical Agglomerative Clustering)</td>
<td>Groups parties by cosine distance in TF-IDF space. No prespecified number of clusters.</td>
<td>Dendrogram showing party linguistic families</td>
</tr>
<tr class="odd">
<td><strong>GMM</strong> (Gaussian Mixture Model)</td>
<td>Soft clustering of party-session documents in PCA space, with BIC-selected number of clusters.</td>
<td>6-cluster solution with probabilistic assignments</td>
</tr>
<tr class="even">
<td><strong>UMAP / t-SNE</strong></td>
<td>Non-linear dimensionality reduction from 3,258 dimensions to 2D for visualization.</td>
<td>Visual map of the document corpus</td>
</tr>
</tbody>
</table>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>The Kozlowski method explained.</strong> An ideological dimension is a direction in word embedding space. The Hindutva dimension, for example, is the vector from the centroid of {secular, minority, mosque, constitution, equality} toward the centroid of {hindu, mandir, temple, cow, ram, ayodhya}. Each party’s position is computed as the TF-IDF-weighted average projection of their full vocabulary onto this direction. The method requires no labelled data. It recovers ideology purely from which words appear in similar contexts.</p>
<p>Source: Kozlowski, Taddy &amp; Evans (2019), <a href="https://doi.org/10.1177/0003122419877135">“The Geometry of Culture”</a>, <em>American Sociological Review</em>.</p>
</div>
</div>
<hr>
</section>
</section>
<section id="findings" class="level2">
<h2 class="anchored" data-anchor-id="findings">Key Findings</h2>
<section id="the-ideological-map-of-indian-parties" class="level3">
<h3 class="anchored" data-anchor-id="the-ideological-map-of-indian-parties">1. The Ideological Map of Indian Parties</h3>
<p>The most direct test of the method: do word embeddings recover a structure that resembles the known ideological landscape of Indian politics?</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="output/figures/ideological_space.png" class="img-fluid figure-img" style="width:85.0%"></p>
<figcaption>Party positions on two ideological dimensions recovered by word2vec. X-axis = economic left to right (positive = more market/growth language). Y-axis = secular to Hindu nationalist (positive = more religious/nationalist vocabulary). Each point is a party’s mean position across all sessions.</figcaption>
</figure>
</div>
<p>The structure matches what a political scientist would draw by hand. BJP and Shiv Sena sit at the Hindu-nationalist pole. Left parties (CPI, CPI-M) and AAP cluster at the secular end. INC occupies the centre-left, consistent with its broad-tent identity.</p>
<p>On the economic axis, the ordering is also informative. BSP and RJD use strongly redistributive, pro-poor language. BJP and TDP skew toward market, investment, and growth vocabulary. AAP sits in an unusual quadrant: secular but economically rightward, which aligns with its urban governance and anti-corruption brand rather than a classic left programme.</p>
<p><strong>Party scores on all three dimensions:</strong></p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Party</th>
<th>Hindutva</th>
<th>Economic Left</th>
<th>Rural/Agrarian</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>JDU</td>
<td>0.189</td>
<td>0.219</td>
<td>0.227</td>
</tr>
<tr class="even">
<td>Shiv Sena</td>
<td>0.057</td>
<td>0.029</td>
<td>0.011</td>
</tr>
<tr class="odd">
<td>BJP</td>
<td>0.026</td>
<td>0.040</td>
<td>-0.049</td>
</tr>
<tr class="even">
<td>TDP</td>
<td>-0.033</td>
<td>-0.221</td>
<td>-0.182</td>
</tr>
<tr class="odd">
<td>RJD</td>
<td>-0.078</td>
<td>0.156</td>
<td>-0.019</td>
</tr>
<tr class="even">
<td>DMK</td>
<td>-0.161</td>
<td>0.036</td>
<td>-0.186</td>
</tr>
<tr class="odd">
<td>INC</td>
<td>-0.174</td>
<td>-0.026</td>
<td>-0.092</td>
</tr>
<tr class="even">
<td>BSP</td>
<td>-0.183</td>
<td>0.316</td>
<td>0.102</td>
</tr>
<tr class="odd">
<td>AAP</td>
<td>-0.274</td>
<td>-0.399</td>
<td>-0.265</td>
</tr>
<tr class="even">
<td>Left</td>
<td>-0.291</td>
<td>-0.162</td>
<td>-0.059</td>
</tr>
<tr class="odd">
<td>SP</td>
<td>-0.292</td>
<td>-0.298</td>
<td>-0.257</td>
</tr>
</tbody>
</table>
<p><em>Positive Hindutva = more nationalist vocabulary. Positive Economic Left = more labour/welfare vocabulary. Positive Rural = more agrarian vocabulary.</em></p>
<hr>
</section>
<section id="bjps-language-has-shifted-over-a-decade-in-government" class="level3">
<h3 class="anchored" data-anchor-id="bjps-language-has-shifted-over-a-decade-in-government">2. BJP’s Language Has Shifted Over a Decade in Government</h3>
<p>The Hindutva score, BJP’s average position on the nationalist dimension, increases monotonically from the 16th to the 18th Lok Sabha.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="output/figures/bjp_hindutva_trajectory.png" class="img-fluid figure-img" style="width:70.0%"></p>
<figcaption>BJP’s mean Hindutva score per Lok Sabha. Higher values indicate more nationalist and religious vocabulary in parliamentary questions. Derived from word2vec projections of the full BJP question corpus.</figcaption>
</figure>
</div>
<p>The shift is not dramatic, but it is consistent and monotonic across all three Lok Sabhas. The language BJP MPs choose when questioning government ministries has moved measurably toward religious and civilisational vocabulary over a decade in power. This is observable without coding a single document by hand.</p>
<hr>
</section>
<section id="topic-discovery-what-parliament-talks-about" class="level3">
<h3 class="anchored" data-anchor-id="topic-discovery-what-parliament-talks-about">3. Topic Discovery: What Parliament Talks About</h3>
<p>LDA identifies 15 latent topics from the corpus. The perplexity curve below shows how model fit improves with more topics; K=15 was selected as the elbow point before diminishing returns.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="output/figures/lda_k_selection.png" class="img-fluid figure-img" style="width:65.0%"></p>
<figcaption>Held-out perplexity as a function of number of topics K. Lower perplexity = better generalization. K=15 selected at the elbow.</figcaption>
</figure>
</div>
<p>The top terms for each topic reveal coherent parliamentary themes.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="output/figures/lda_top_terms.png" class="img-fluid figure-img" style="width:100.0%"></p>
<figcaption>Top terms per LDA topic by four ranking methods (probability, FREX, lift, score). Each column is one topic.</figcaption>
</figure>
</div>
<p>The topics that emerge include: railway and transport infrastructure, agricultural welfare and farmer issues, sugar industry and pricing, judicial and electoral matters, public health and AIIMS, education and universities, water resources and river projects, petroleum and energy, defence and border security, and state-level budgetary allocations.</p>
<p><strong>Topic distribution by party:</strong></p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="output/figures/lda_party_heatmap.png" class="img-fluid figure-img" style="width:90.0%"></p>
<figcaption>LDA topic heatmap. Rows = 15 topics, columns = parties. Colour intensity = average topic weight. Brighter = that party more strongly emphasises the topic.</figcaption>
</figure>
</div>
<p>BJP concentrates on infrastructure, defence, and state-level development. INC focuses on governance, accountability, and judicial matters. Left parties show strong concentration on labour, wages, and public sector employment. Regional parties show sharp, idiosyncratic peaks consistent with their state-specific mandates: NCP on Maharashtra agriculture, DMK on Tamil Nadu water disputes and Dravidian cultural issues.</p>
<hr>
</section>
<section id="structural-topic-model-party-effects-and-time-trends" class="level3">
<h3 class="anchored" data-anchor-id="structural-topic-model-party-effects-and-time-trends">4. Structural Topic Model: Party Effects and Time Trends</h3>
<p>The Structural Topic Model extends LDA by allowing party identity and Lok Sabha number to predict topic prevalence directly, estimating a marginal effect for each covariate on each topic.</p>
<div class="quarto-layout-panel" data-layout-ncol="2">
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="output/figures/stm_effects_lok.png" class="img-fluid figure-img"></p>
<figcaption>STM topic effects of Lok Sabha number. Red dots indicate topics whose prevalence changed significantly (p &lt; 0.05) across the 16th, 17th, and 18th Lok Sabha. Positive = growing topic; negative = declining topic.</figcaption>
</figure>
</div>
</div>
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="output/figures/stm_bjp_inc_contrast.png" class="img-fluid figure-img"></p>
<figcaption>BJP vs INC topic contrast. Each point is one topic. X-axis = marginal INC effect; Y-axis = marginal BJP effect. Topics in the upper-left are BJP-specific; topics in the lower-right are INC-specific.</figcaption>
</figure>
</div>
</div>
</div>
</div>
<p>The time trend plot shows which topics have grown or shrunk in parliamentary questioning across the three Lok Sabhas. The BJP-INC contrast plot shows the topics most differentially associated with each party, net of the overall topic distribution. Topics in the upper-left quadrant are distinctively BJP; those in the lower-right are distinctively INC.</p>
<hr>
</section>
<section id="the-document-map" class="level3">
<h3 class="anchored" data-anchor-id="the-document-map">5. The Document Map</h3>
<p>Each of the 205 party-session documents projected from the full 3,258-term TF-IDF space into 2D. Two projection methods side by side: UMAP (preserves global structure) and t-SNE (emphasises local cluster separation).</p>
<div class="quarto-layout-panel" data-layout-ncol="2">
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="output/figures/umap_party_session.png" class="img-fluid figure-img"></p>
<figcaption>UMAP projection of 205 party-session documents. Each point is one party in one parliamentary session. Proximity indicates similar vocabulary. Points coloured by party.</figcaption>
</figure>
</div>
</div>
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="output/figures/tsne_party_session.png" class="img-fluid figure-img"></p>
<figcaption>t-SNE projection of the same 205 documents. t-SNE uses a different cost function that sharpens local clusters at the cost of global structure.</figcaption>
</figure>
</div>
</div>
</div>
</div>
<p>Both methods agree on the broad structure. BJP and INC form the two largest and most central clusters, reflecting their dominant presence across all sessions. Left parties cluster tightly together. Regional parties scatter to the periphery, consistent with their narrow, state-specific focus. The two methods differ mainly in how compressed the regional party cloud appears, with t-SNE pulling the smaller parties further apart.</p>
<hr>
</section>
<section id="clustering-which-parties-use-similar-language" class="level3">
<h3 class="anchored" data-anchor-id="clustering-which-parties-use-similar-language">6. Clustering: Which Parties Use Similar Language?</h3>
<p>Two clustering approaches applied to the same TF-IDF party vectors: hierarchical agglomerative clustering, which builds a dendrogram without requiring a prespecified number of clusters, and Gaussian mixture modelling in PCA space, which yields a soft probabilistic assignment.</p>
<div class="quarto-layout-panel" data-layout-ncol="2">
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="output/figures/hac_dendrogram.png" class="img-fluid figure-img"></p>
<figcaption>Hierarchical clustering dendrogram. Height = cosine distance between party TF-IDF vectors. Parties that merge at low heights use very similar parliamentary language.</figcaption>
</figure>
</div>
</div>
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="output/figures/gmm_pca_clusters.png" class="img-fluid figure-img"></p>
<figcaption>GMM clustering in PCA space. BIC-selected solution: 6 clusters. Points coloured by cluster assignment. Party labels indicate mean cluster position.</figcaption>
</figure>
</div>
</div>
</div>
</div>
<p>The dendrogram reveals a clear structure: BJP and NDA-aligned parties (JDU, TDP) cluster together, reflecting shared government priorities. INC, SP, and BSP form a second cluster with a common welfare-oriented vocabulary. Left parties sit as a tight sub-cluster within the opposition grouping. Regional parties (TMC, DMK, AIADMK) form a separate branch.</p>
<p>The GMM solution with 6 clusters roughly tracks this structure but further separates the micro-regional parties that appear in only one Lok Sabha.</p>
<p><strong>Party positions in PCA-cluster space:</strong></p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="output/figures/embedding_clusters.png" class="img-fluid figure-img" style="width:80.0%"></p>
<figcaption>Embedding clusters: party positions in the first two principal components of TF-IDF space, with GMM cluster colouring overlaid.</figcaption>
</figure>
</div>
<hr>
</section>
<section id="ministry-focus-where-each-party-directs-its-questions" class="level3">
<h3 class="anchored" data-anchor-id="ministry-focus-where-each-party-directs-its-questions">7. Ministry Focus: Where Each Party Directs Its Questions</h3>
<p>Parliamentary questions are addressed to specific ministries. The heatmap below shows each party’s distribution of questions across ministries, revealing surveillance priorities.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="output/figures/ministry_heatmap.png" class="img-fluid figure-img" style="width:90.0%"></p>
<figcaption>Ministry focus heatmap. Colour = share of questions directed at each ministry, by party. Reveals which policy domains each party watches most closely.</figcaption>
</figure>
</div>
<p>BJP MPs question the Ministry of Railways and Road Transport heavily, consistent with the party’s infrastructure-first governance brand. INC concentrates on Finance, Home Affairs, and External Affairs, the domains of national accountability. Left parties direct disproportionate attention to Labour and Employment. Regional parties show ministry distributions that closely track their state’s economic profile: DMK on Textiles and Fisheries, TDP on Agriculture.</p>
<hr>
</section>
<section id="how-topics-have-evolved-over-time" class="level3">
<h3 class="anchored" data-anchor-id="how-topics-have-evolved-over-time">8. How Topics Have Evolved Over Time</h3>
<p>Topic composition across parliamentary sessions, shown separately for BJP and INC to highlight how each party’s agenda has shifted.</p>
<div class="quarto-layout-panel" data-layout-ncol="2">
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="output/figures/topic_stacked_bjp.png" class="img-fluid figure-img"></p>
<figcaption>BJP topic evolution across sessions of the 16th and 17th Lok Sabha. Each band is one LDA topic. Width = share of that session’s BJP questions attributed to the topic.</figcaption>
</figure>
</div>
</div>
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="output/figures/topic_stacked_inc.png" class="img-fluid figure-img"></p>
<figcaption>INC topic evolution across the same period. INC was in opposition for both the 16th and 17th Lok Sabha, which shapes what it chooses to question.</figcaption>
</figure>
</div>
</div>
</div>
</div>
<p>BJP’s topic mix shifts noticeably between the 16th and 17th Lok Sabha, with infrastructure and agriculture topics expanding. INC’s mix is more stable but shows a gradual shift toward governance and institutional accountability topics, consistent with an opposition party trying to hold government to account on process rather than policy.</p>
<hr>
</section>
<section id="semantic-neighbours-of-key-political-terms" class="level3">
<h3 class="anchored" data-anchor-id="semantic-neighbours-of-key-political-terms">9. Semantic Neighbours of Key Political Terms</h3>
<p>The word2vec embedding trained on 150K questions allows us to ask: what words appear in the most similar contexts to a given political term? The nearest neighbours reveal how concepts are linguistically entangled in Indian parliamentary discourse.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="output/figures/semantic_neighbors.png" class="img-fluid figure-img" style="width:100.0%"></p>
<figcaption>Nearest neighbours in embedding space for ten politically salient seed words. Each panel shows the eight closest words by cosine similarity.</figcaption>
</figure>
</div>
<p>Some findings worth noting. “Farmer” sits close to drought, MSP, irrigation, and kisan, placing it firmly in a welfare-scarcity frame rather than an entrepreneurial one. “Terrorism” clusters with border, security, and Pakistan rather than with domestic extremism terms, indicating how the term is deployed in parliamentary questioning. “Caste” is proximate to reservation, OBC, and scheduled, pointing to its institutional rather than sociological usage in Parliament. “Corruption” sits close to scam, irregularity, and vigilance, reflecting the procedural register in which MPs raise accountability concerns.</p>
<hr>
</section>
<section id="summary-panel" class="level3">
<h3 class="anchored" data-anchor-id="summary-panel">10. Summary Panel</h3>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="output/figures/final_summary_panel.png" class="img-fluid figure-img" style="width:100.0%"></p>
<figcaption>Combined summary panel: ideological space (top left), UMAP (top right), BJP Hindutva trajectory (bottom left), and topic evolution (bottom right).</figcaption>
</figure>
</div>
<hr>
</section>
</section>
<section id="reproduce" class="level2">
<h2 class="anchored" data-anchor-id="reproduce">Reproducing the Analysis</h2>
<p><strong>Requirements:</strong> R 4.3+. All packages install automatically.</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">source</span>(<span class="st">"code/_master.R"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>The master file downloads all data from HuggingFace (no account needed), installs dependencies, and runs the full pipeline A1 through A8. Total runtime is roughly 15 minutes on a modern laptop. The word2vec training step is the most compute-intensive; it is cached after the first run.</p>
<p><strong>Full code and data on <a href="https://github.com/pzaware19/lok-sabha-nlp">GitHub</a>.</strong></p>
<hr>
</section>
<section id="about" class="level2">
<h2 class="anchored" data-anchor-id="about">About</h2>
<p><strong>Piyush Zaware</strong></p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
            // target, if specified
            link.setAttribute("target", "_blank");
            if (link.getAttribute("rel") === null) {
              link.setAttribute("rel", "noopener");
            }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
      &nbsp;
    </div>   
    <div class="nav-footer-center">
<p>Piyush Zaware</p>
</div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>




<script src="site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>